


WITH TEMP(EMP_ID, MAN_ID) AS
(
SELECT E1.EMP_ID, E1.MAN_ID
FROM EMP E1
WHERE E1.EMP_ID = 19
UNION ALL
SELECT TEMP.MAN_ID, E2.MAN_ID FROM TEMP
JOIN EMP E2 ON TEMP.MAN_ID = E2.EMP_ID
)
SELECT TEMP.EMP_ID, TEMP.MAN_ID FROM TEMP;