SELECT E1.EMP_ID
FROM EMP E1
LEFT JOIN EMP E2 ON E1.EMP_ID = E2.MAN_ID
WHERE E2.EMP_ID IS NULL
ORDER BY E1.EMP_ID;
--GROUP BY E1.EMP_ID
--HAVING COUNT(E2.EMP_ID) = 0;


SELECT E1.EMP_ID
FROM EMP E1
LEFT JOIN EMP E2 ON E1.EMP_ID = E2.MAN_ID
GROUP BY E1.EMP_ID
HAVING COUNT(E2.EMP_ID) = 0
ORDER BY E1.EMP_ID;