SELECT TOP_MANAGER AS EMP_ID, COUNT(EMP_ID) AS SUBS_COUNT
FROM (
WITH CTE(EMP_ID, NAME, MAN_ID, TOP_MANAGER)
AS
(
    SELECT E1.EMP_ID, E1.NAME, E1.MAN_ID, E1.EMP_ID AS TOP_MANAGER
    FROM EMP E1
        UNION ALL
    SELECT E2.EMP_ID, E2.NAME, E2.MAN_ID, CTE.TOP_MANAGER
    FROM EMP E2
    INNER JOIN CTE ON E2.MAN_ID = CTE.EMP_ID
)
SELECT CTE.EMP_ID, CTE.TOP_MANAGER
FROM CTE)
GROUP BY TOP_MANAGER
ORDER BY SUBS_COUNT DESC;