WITH TREE(NAME, EMP_ID, LEV, PATHSTR)
AS
(
  SELECT EMP.NAME, EMP.EMP_ID, 1, EMP.NAME
  FROM EMP
  WHERE EMP.MAN_ID IS NULL
UNION ALL
  SELECT EMP.NAME, EMP.EMP_ID, TREE.LEV + 1, TREE.PATHSTR || EMP.NAME
  FROM EMP
  JOIN TREE ON TREE.EMP_ID = EMP.MAN_ID
)
SELECT TREE.EMP_ID, LPAD(NAME, TREE.LEV, ' ') AS NAME, TREE.LEV, TREE.PATHSTR
FROM TREE
ORDER BY TREE.PATHSTR;

/*
1	1	A	A
2	2	AB	 B
6	3	ABF	  F
14	4	ABFN	   N
15	4	ABFO	   O
7	3	ABG	  G
16	4	ABGP	   P
8	3	ABH	  H
3	2	AC	 C
9	3	ACI	  I
17	4	ACIQ	   Q
18	4	ACIR	   R
10	3	ACJ	  J
4	2	AD	 D
11	3	ADK	  K
19	4	ADKS	   S
12	3	ADL	  L
5	2	AE	 E
13	3	AEM	  M
*/